/**
 * Exit-intent 쿠폰 게이트 — BGWidget.prototype.initExitIntent 정의
 *
 * buttons.ts WIDGET_JS IIFE 내부에 인라인 삽입됨.
 * 의존: PROVIDERS, escapeHtml, BGWidget (IIFE 스코프), window.__BG_TRIGGERS__
 *
 * 작동 조건:
 *   1. shop.plan === 'plus'
 *   2. 비회원 (isUserLoggedIn() === false)
 *   3. exit_intent_config.enabled === true
 *   4. shouldShowEvent('exit_intent', capHours) 통과
 *
 * funnel 이벤트:
 *   widget.exit_intent_shown / widget.exit_intent_signup / widget.exit_intent_dismissed
 *   widget.scroll_trigger_fired
 */
export function getExitIntentJs(): string {
  return [
    '  // ─── Exit-intent 쿠폰 게이트 ─────────────────────────────────',
    '  BGWidget.prototype.initExitIntent = function(config) {',
    '    var self = this;',
    '    var ei = config.exit_intent_config;',
    '    if (!ei || ei.enabled === false) return;',
    '    if (self.isUserLoggedIn()) return;',
    '    var triggers = window.__BG_TRIGGERS__;',
    '    if (!triggers) return;',
    '    var capHours = typeof ei.frequency_cap_hours === "number" ? ei.frequency_cap_hours : 24;',
    '    var headline = ei.headline || "\\uc7a0\\uae4c\\ub9cc\\uc694!";',  // 잠깐만요!
    '    var body = ei.body || "\\uc9c0\\uae08 \\uac00\\uc785\\ud558\\uba74 \\uc989\\uc2dc \\ud61c\\ud0dd\\uc744 \\ubc1b\\uc744 \\uc218 \\uc788\\uc5b4\\uc694.";',
    '    var couponLabel = "";',
    '    try {',
    '      var couponCfg = config.coupon_config || {};',
    '      var couponType = ei.coupon_type;',
    '      if (couponType && couponCfg[couponType] && couponCfg[couponType].enabled) {',
    '        var cDef = couponCfg[couponType];',
    '        if (couponType === "shipping") { couponLabel = "\\ubb34\\ub8cc\\ubc30\\uc1a1 \\ucfe0\\ud3f0"; }',  // 무료배송 쿠폰
    '        else if (couponType === "amount") { couponLabel = (cDef.discount_amount ? cDef.discount_amount.toLocaleString() + "\\uc6d0 \\ud560\\uc778 \\ucfe0\\ud3f0" : "\\ud560\\uc778 \\ucfe0\\ud3f0"); }',
    '        else if (couponType === "rate") { couponLabel = (cDef.discount_rate ? cDef.discount_rate + "% \\ud560\\uc778 \\ucfe0\\ud3f0" : "\\ud560\\uc778 \\ucfe0\\ud3f0"); }',
    '      }',
    '    } catch (e) {}',
    '    var shown = false;',
    '    function showExitIntentModal() {',
    '      if (shown) return;',
    '      shown = true;',
    '      self.trackEvent("widget.exit_intent_shown", {});',
    '      var overlay = document.createElement("div");',
    '      overlay.style.cssText = "position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.55);z-index:9999;display:flex;align-items:center;justify-content:center";',
    '      if (!document.getElementById("bg-ei-style")) {',
    '        var st = document.createElement("style");',
    '        st.id = "bg-ei-style";',
    '        st.textContent = "@keyframes bg-ei-fadein{from{opacity:0}to{opacity:1}}@keyframes bg-ei-slidein{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}";',
    '        document.head.appendChild(st);',
    '      }',
    '      overlay.style.animation = "bg-ei-fadein 0.25s ease";',
    '      var modal = document.createElement("div");',
    '      modal.style.cssText = "background:#ffffff;padding:32px 28px 24px;max-width:400px;width:calc(100% - 32px);border-radius:16px;box-shadow:0 24px 80px rgba(0,0,0,0.28);position:relative;animation:bg-ei-slidein 0.3s ease;box-sizing:border-box";',
    '      var s = (config.style) || {};',
    '      var preset = s.preset || "default";',
    '      var DARK_PRESETS = {"glassmorphism":1,"neon-glow":1,"liquid-glass":1,"gradient-flow":1};',
    '      if (DARK_PRESETS[preset]) {',
    '        modal.style.background = "#1a1a2e";',
    '      }',
    '      var closeBtn = document.createElement("button");',
    '      closeBtn.style.cssText = "position:absolute;top:12px;right:16px;background:none;border:none;font-size:20px;cursor:pointer;color:#9ca3af;padding:4px 8px;line-height:1";',
    '      closeBtn.textContent = "\\u00d7";',
    '      closeBtn.addEventListener("click", function() {',
    '        overlay.remove();',
    '        self.trackEvent("widget.exit_intent_dismissed", {});',
    '      });',
    '      var titleEl = document.createElement("h3");',
    '      titleEl.textContent = headline;',
    '      titleEl.style.cssText = "font-size:22px;font-weight:700;color:" + (DARK_PRESETS[preset] ? "#f9fafb" : "#111827") + ";margin:0 0 10px;text-align:center;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif";',
    '      var bodyEl = document.createElement("p");',
    '      var displayBody = couponLabel ? body.replace("{coupon}", couponLabel) : body;',
    '      bodyEl.style.cssText = "font-size:14px;color:" + (DARK_PRESETS[preset] ? "#9ca3af" : "#4b5563") + ";text-align:center;margin:0 0 16px;line-height:1.6;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif";',
    '      bodyEl.innerHTML = escapeHtml(displayBody).replace(/\\n/g, "<br>");',
    '      var badgeEl = null;',
    '      if (couponLabel) {',
    '        badgeEl = document.createElement("div");',
    '        badgeEl.textContent = couponLabel;',
    '        badgeEl.style.cssText = "display:block;text-align:center;background:#fef3c7;color:#92400e;border:1px solid #fde68a;border-radius:6px;padding:4px 12px;font-size:13px;font-weight:600;margin-bottom:18px";',
    '      }',
    '      var btnWrap = document.createElement("div");',
    '      btnWrap.style.cssText = "display:flex;flex-direction:column;gap:8px;margin-bottom:14px";',
    '      var providers = (config.providers && config.providers.length > 0) ? config.providers : [];',
    '      for (var i = 0; i < providers.length; i++) {',
    '        var prov = providers[i];',
    '        var pInfo = PROVIDERS[prov];',
    '        if (!pInfo) continue;',
    '        var pBtn = document.createElement("button");',
    '        var pBg = pInfo.bgColor;',
    '        var pTc = pInfo.textColor;',
    '        pBtn.style.cssText = "display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:11px 16px;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;border:none;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;transition:opacity 0.15s;background:" + pBg + ";color:" + pTc;',
    '        if (pBg === "#f2f2f2" || pBg === "#FFFFFF" || pBg === "#ffffff") { pBtn.style.border = "1px solid #dadce0"; }',
    '        var iconEl = document.createElement("span");',
    '        iconEl.innerHTML = pInfo.icon;',
    '        pBtn.appendChild(iconEl);',
    '        var lbl = document.createElement("span");',
    '        lbl.textContent = pInfo.name + "\\ub85c \\uac00\\uc785\\ud558\\uae30";',  // 로 가입하기
    '        pBtn.appendChild(lbl);',
    '        pBtn.addEventListener("mouseenter", function() { this.style.opacity = "0.85"; });',
    '        pBtn.addEventListener("mouseleave", function() { this.style.opacity = "1"; });',
    '        (function(provider) {',
    '          pBtn.addEventListener("click", function() {',
    '            overlay.remove();',
    '            self.trackEvent("widget.exit_intent_signup", { provider: provider });',
    '            self.startAuth(provider);',
    '          });',
    '        })(prov);',
    '        btnWrap.appendChild(pBtn);',
    '      }',
    '      var dismissLink = document.createElement("button");',
    '      dismissLink.textContent = "\\uadf8\\ub0e5 \\ub2eb\\uae30";',  // 그냥 닫기
    '      dismissLink.style.cssText = "display:block;width:100%;background:none;border:none;color:#9ca3af;font-size:13px;cursor:pointer;padding:8px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;text-align:center";',
    '      dismissLink.addEventListener("click", function() {',
    '        overlay.remove();',
    '        self.trackEvent("widget.exit_intent_dismissed", {});',
    '      });',
    '      modal.appendChild(closeBtn);',
    '      modal.appendChild(titleEl);',
    '      modal.appendChild(bodyEl);',
    '      if (badgeEl) modal.appendChild(badgeEl);',
    '      modal.appendChild(btnWrap);',
    '      modal.appendChild(dismissLink);',
    '      overlay.appendChild(modal);',
    '      overlay.addEventListener("click", function(e) {',
    '        if (e.target === overlay) { overlay.remove(); self.trackEvent("widget.exit_intent_dismissed", {}); }',
    '      });',
    '      document.body.appendChild(overlay);',
    '    }',
    '    if (triggers.shouldShowEvent("exit_intent", capHours)) {',
    '      triggers.registerTrigger(',
    '        { eventKey: "exit_intent", mode: "exit-intent", capHours: capHours },',
    '        showExitIntentModal',
    '      );',
    '      var scrollDepth = typeof ei.scroll_depth_threshold === "number" ? ei.scroll_depth_threshold : 0;',
    '      if (scrollDepth > 0) {',
    '        triggers.registerTrigger(',
    '          { eventKey: "scroll_trigger", mode: "scroll-depth", threshold: scrollDepth, capHours: capHours },',
    '          function() {',
    '            self.trackEvent("widget.scroll_trigger_fired", { threshold: scrollDepth });',
    '            showExitIntentModal();',
    '          }',
    '        );',
    '      }',
    '    }',
    '  };',
  ].join('\n');
}
