/**
 * DEPRECATED — 2026-04-29 이탈 팝업(initExitPopup)으로 흡수됨.
 * 1개월 후 삭제 예정 (2026-05-29).
 *
 * Exit-intent 단독 기능 폐기 (D1=A 결정):
 *   - initExitIntent() 호출 제거 (buttons.ts loadConfig 참조)
 *   - exit_intent_config는 데이터 보존 (롤백 옵션). 차후 마이그레이션에서 컬럼 삭제.
 *   - 위젯은 이제 popup_config 기준으로만 동작.
 *
 * @deprecated Use initExitPopup in buttons.ts instead.
 */
export function getExitIntentJs(): string {
  // DEPRECATED: 이 함수는 더 이상 buttons.ts에서 호출되지 않습니다.
  // 이탈 팝업(initExitPopup)으로 기능이 흡수되었습니다.
  return [
    '  // ─── Exit-intent (DEPRECATED — initExitPopup으로 흡수됨) ────',
    '  BGWidget.prototype.initExitIntent = function() {',
    '    // DEPRECATED: 이 메서드는 호출되지 않습니다. initExitPopup을 사용하세요.',
    '    if (typeof console !== "undefined" && console.warn) {',
    '      console.warn("[번개가입] initExitIntent is deprecated. Use initExitPopup.");',
    '    }',
    '  };',
  ].join('\n');
}

/*
 * 아래는 레거시 구현 보관 (롤백 참조용) — 2026-05-29 이후 전체 삭제 예정.
 *
function getExitIntentJsLegacy(): string {
  return [
    '  // ─── Exit-intent 쿠폰 게이트 ─────────────────────────────────',
    '  BGWidget.prototype.initExitIntent = function(config) {',
    '    var self = this;',
    '    var ei = config.exit_intent_config;',
    '    if (!ei || ei.enabled === false) return;',
    '    if (self.isUserLoggedIn()) return;',
    '    var triggers = window.__BG_TRIGGERS__;',
    '    if (!triggers) return;',
    '    var capHours = typeof ei.frequency_cap_hours === "number" ? ei.frequency_cap_hours : 24;',
    '    var headline = ei.headline || "\\uc7a0\\uae4c\\ub9cc\\uc694!";',  // 잠깐만요!
    '    var body = ei.body || "\\uc9c0\\uae08 \\uac00\\uc785\\ud558\\uba74 \\uc989\\uc2dc \\ud61c\\ud0dd\\uc744 \\ubc1b\\uc744 \\uc218 \\uc788\\uc5b4\\uc694.";',
    '    var couponLabel = "";',
    '    try {',
    '      var couponCfg = config.coupon_config || {};',
    '      var couponType = ei.coupon_type;',
    '      if (couponType && couponCfg[couponType] && couponCfg[couponType].enabled) {',
    '        var cDef = couponCfg[couponType];',
    '        if (couponType === "shipping") { couponLabel = "\\ubb34\\ub8cc\\ubc30\\uc1a1 \\ucfe0\\ud3f0"; }',  // 무료배송 쿠폰
    '        else if (couponType === "amount") { couponLabel = (cDef.discount_amount ? cDef.discount_amount.toLocaleString() + "\\uc6d0 \\ud560\\uc778 \\ucfe0\\ud3f0" : "\\ud560\\uc778 \\ucfe0\\ud3f0"); }',
    '        else if (couponType === "rate") { couponLabel = (cDef.discount_rate ? cDef.discount_rate + "% \\ud560\\uc778 \\ucfe0\\ud3f0" : "\\ud560\\uc778 \\ucfe0\\ud3f0"); }',
    '      }',
    '    } catch (e) {}',
    '    var shown = false;',
    '    function showExitIntentModal() {',
    '      if (shown) return;',
    '      shown = true;',
    '      self.trackEvent("widget.exit_intent_shown", {});',
    '      var overlay = document.createElement("div");',
    '      overlay.style.cssText = "position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.55);z-index:9999;display:flex;align-items:center;justify-content:center";',
    '      if (!document.getElementById("bg-ei-style")) {',
    '        var st = document.createElement("style");',
    '        st.id = "bg-ei-style";',
    '        st.textContent = "@keyframes bg-ei-fadein{from{opacity:0}to{opacity:1}}@keyframes bg-ei-slidein{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}";',
    '        document.head.appendChild(st);',
    '      }',
    '      overlay.style.animation = "bg-ei-fadein 0.25s ease";',
    '      var modal = document.createElement("div");',
    '      modal.style.cssText = "background:#ffffff;padding:32px 28px 24px;max-width:400px;width:calc(100% - 32px);border-radius:16px;box-shadow:0 24px 80px rgba(0,0,0,0.28);position:relative;animation:bg-ei-slidein 0.3s ease;box-sizing:border-box";',
    '      var s = (config.style) || {};',
    '      var preset = s.preset || "default";',
    '      var DARK_PRESETS = {"glassmorphism":1,"neon-glow":1,"liquid-glass":1,"gradient-flow":1};',
    '      if (DARK_PRESETS[preset]) {',
    '        modal.style.background = "#1a1a2e";',
    '      }',
    '      var closeBtn = document.createElement("button");',
    '      closeBtn.style.cssText = "position:absolute;top:12px;right:16px;background:none;border:none;font-size:20px;cursor:pointer;color:#9ca3af;padding:4px 8px;line-height:1";',
    '      closeBtn.textContent = "\\u00d7";',
    '      closeBtn.addEventListener("click", function() {',
    '        overlay.remove();',
    '        self.trackEvent("widget.exit_intent_dismissed", {});',
    '      });',
    '      var titleEl = document.createElement("h3");',
    '      titleEl.textContent = headline;',
    '      titleEl.style.cssText = "font-size:22px;font-weight:700;color:" + (DARK_PRESETS[preset] ? "#f9fafb" : "#111827") + ";margin:0 0 10px;text-align:center;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif";',
    '      var bodyEl = document.createElement("p");',
    '      var displayBody = couponLabel ? body.replace("{coupon}", couponLabel) : body;',
    '      bodyEl.style.cssText = "font-size:14px;color:" + (DARK_PRESETS[preset] ? "#9ca3af" : "#4b5563") + ";text-align:center;margin:0 0 16px;line-height:1.6;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif";',
    '      bodyEl.innerHTML = escapeHtml(displayBody).replace(/\\n/g, "<br>");',
    '      var badgeEl = null;',
    '      if (couponLabel) {',
    '        badgeEl = document.createElement("div");',
    '        badgeEl.textContent = couponLabel;',
    '        badgeEl.style.cssText = "display:block;text-align:center;background:#fef3c7;color:#92400e;border:1px solid #fde68a;border-radius:6px;padding:4px 12px;font-size:13px;font-weight:600;margin-bottom:18px";',
    '      }',
    '      // Plus 쿠폰팩 카드 (pack.state === \'active\' && plan !== \'free\' 분기)',
    '      var cpConfig = config.coupon_pack;',
    '      var cpCardEl = null;',
    '      if (cpConfig && cpConfig.active) {',
    '        cpCardEl = self.renderCouponPackCard(cpConfig);',
    '        self.trackEvent("widget.coupon_pack_shown", {',
    '          source: "exit_intent",',
    '          design: cpConfig.design || "brand",',
    '          anim_mode: cpConfig.anim_mode !== false,',
    '          total_amount: cpConfig.total_amount || 55000',
    '        });',
    '      }',
    '      var btnWrap = document.createElement("div");',
    '      btnWrap.style.cssText = "display:flex;flex-direction:column;gap:8px;margin-bottom:14px";',
    '      var providers = (config.providers && config.providers.length > 0) ? config.providers : [];',
    '      for (var i = 0; i < providers.length; i++) {',
    '        var prov = providers[i];',
    '        var pInfo = PROVIDERS[prov];',
    '        if (!pInfo) continue;',
    '        var pBtn = document.createElement("button");',
    '        var pBg = pInfo.bgColor;',
    '        var pTc = pInfo.textColor;',
    '        pBtn.style.cssText = "display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:11px 16px;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;border:none;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;transition:opacity 0.15s;background:" + pBg + ";color:" + pTc;',
    '        if (pBg === "#f2f2f2" || pBg === "#FFFFFF" || pBg === "#ffffff") { pBtn.style.border = "1px solid #dadce0"; }',
    '        var iconEl = document.createElement("span");',
    '        iconEl.innerHTML = pInfo.icon;',
    '        pBtn.appendChild(iconEl);',
    '        var lbl = document.createElement("span");',
    '        var btnText = cpCardEl ? "\\ud68c\\uc6d0\\uac00\\uc785 \\u2192" : pInfo.name + "\\ub85c \\uac00\\uc785\\ud558\\uae30";',  // "회원가입 →" or "OO로 가입하기"
    '        lbl.textContent = btnText;',
    '        pBtn.appendChild(lbl);',
    '        pBtn.addEventListener("mouseenter", function() { this.style.opacity = "0.85"; });',
    '        pBtn.addEventListener("mouseleave", function() { this.style.opacity = "1"; });',
    '        (function(provider) {',
    '          pBtn.addEventListener("click", function() {',
    '            overlay.remove();',
    '            self.trackEvent("widget.exit_intent_signup", { provider: provider });',
    '            if (cpCardEl) {',
    '              self.trackEvent("widget.coupon_pack_clicked", {',
    '                source: "exit_intent",',
    '                design: cpConfig.design || "brand",',
    '                total_amount: cpConfig.total_amount || 55000',
    '              });',
    '            }',
    '            self.startAuth(provider);',
    '          });',
    '        })(prov);',
    '        btnWrap.appendChild(pBtn);',
    '      }',
    '      var dismissLink = document.createElement("button");',
    '      dismissLink.textContent = "\\uadf8\\ub0e5 \\ub2eb\\uae30";',  // 그냥 닫기
    '      dismissLink.style.cssText = "display:block;width:100%;background:none;border:none;color:#9ca3af;font-size:13px;cursor:pointer;padding:8px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;text-align:center";',
    '      dismissLink.addEventListener("click", function() {',
    '        overlay.remove();',
    '        self.trackEvent("widget.exit_intent_dismissed", {});',
    '      });',
    '      modal.appendChild(closeBtn);',
    '      modal.appendChild(titleEl);',
    '      modal.appendChild(bodyEl);',
    '      if (badgeEl) modal.appendChild(badgeEl);',
    '      // 쿠폰팩 카드 (Plus 플랜, state=active): body 아래, 소셜 버튼 위에 배치',
    '      if (cpCardEl) modal.appendChild(cpCardEl);',
    '      modal.appendChild(btnWrap);',
    '      modal.appendChild(dismissLink);',
    '      overlay.appendChild(modal);',
    '      overlay.addEventListener("click", function(e) {',
    '        if (e.target === overlay) { overlay.remove(); self.trackEvent("widget.exit_intent_dismissed", {}); }',
    '      });',
    '      document.body.appendChild(overlay);',
    '    }',
    '    if (triggers.shouldShowEvent("exit_intent", capHours)) {',
    '      triggers.registerTrigger(',
    '        { eventKey: "exit_intent", mode: "exit-intent", capHours: capHours },',
    '        showExitIntentModal',
    '      );',
    '      var scrollDepth = typeof ei.scroll_depth_threshold === "number" ? ei.scroll_depth_threshold : 0;',
    '      if (scrollDepth > 0) {',
    '        triggers.registerTrigger(',
    '          { eventKey: "scroll_trigger", mode: "scroll-depth", threshold: scrollDepth, capHours: capHours },',
    '          function() {',
    '            self.trackEvent("widget.scroll_trigger_fired", { threshold: scrollDepth });',
    '            showExitIntentModal();',
    '          }',
    '        );',
    '      }',
    '    }',
    '  };',
  ].join('\n');
}
*/
