/**
 * Smart Trigger Engine — 번개가입 위젯용 클라이언트 사이드 트리거 엔진
 *
 * ScriptTag로 inject되므로 외부 라이브러리 X, 순수 JS.
 * buttons.ts WIDGET_JS IIFE 내부에 인라인 삽입됨.
 *
 * 공개 API (window.__BG_TRIGGERS__):
 *   shouldShowEvent(eventKey, capHours?)  → boolean
 *   markEventSeen(eventKey, capHours?)    → void
 *   onScrollDepth(percent, callback)      → void
 *   registerTrigger(options, callback)    → void
 */
export function getSmartTriggerJs(): string {
  return [
    '  // ─── Smart Trigger Engine ──────────────────────────────────────',
    '  if (!window.__BG_TRIGGERS__) {',
    '    var _BGT = {};',
    '    _BGT.shouldShowEvent = function(eventKey, capHours) {',
    '      var hours = (typeof capHours === "number") ? capHours : 24;',
    '      var cookieName = "bg_seen_" + eventKey;',
    '      try {',
    '        var match = document.cookie.match(new RegExp("(?:^|; ?)" + cookieName + "=([^;]+)"));',
    '        if (match) {',
    '          var lastSeenMs = new Date(decodeURIComponent(match[1])).getTime();',
    '          if (!isNaN(lastSeenMs) && Date.now() - lastSeenMs < hours * 3600 * 1000) return false;',
    '        }',
    '      } catch (e) {}',
    '      return true;',
    '    };',
    '    _BGT.markEventSeen = function(eventKey, capHours) {',
    '      var hours = (typeof capHours === "number") ? capHours : 24;',
    '      var cookieName = "bg_seen_" + eventKey;',
    '      var expires = new Date(Date.now() + hours * 3600 * 1000).toUTCString();',
    '      document.cookie = cookieName + "=" + encodeURIComponent(new Date().toISOString())',
    '        + "; expires=" + expires + "; path=/; SameSite=Lax";',
    '    };',
    '    _BGT.onScrollDepth = function(percent, callback) {',
    '      var fired = false;',
    '      function check() {',
    '        if (fired) return;',
    '        var scrollTop = window.scrollY || document.documentElement.scrollTop;',
    '        var docH = Math.max(document.body.scrollHeight, document.documentElement.scrollHeight,',
    '          document.body.offsetHeight, document.documentElement.offsetHeight);',
    '        var vpH = window.innerHeight;',
    '        var scrollable = docH - vpH;',
    '        if (scrollable <= 0) return;',
    '        if ((scrollTop / scrollable) * 100 >= percent) {',
    '          fired = true;',
    '          try { callback(); } catch (e) {}',
    '        }',
    '      }',
    '      if ("IntersectionObserver" in window) {',
    '        var sentinel = document.createElement("div");',
    '        sentinel.style.cssText = "position:absolute;left:0;width:1px;height:1px;visibility:hidden";',
    '        var tgtOff = Math.floor((document.body.scrollHeight || 0) * (percent / 100));',
    '        sentinel.style.top = tgtOff + "px";',
    '        document.body.appendChild(sentinel);',
    '        var io = new IntersectionObserver(function(entries) {',
    '          for (var i = 0; i < entries.length; i++) {',
    '            if (entries[i].isIntersecting && !fired) {',
    '              fired = true; io.disconnect(); sentinel.remove();',
    '              try { callback(); } catch (e) {}',
    '            }',
    '          }',
    '        }, { threshold: 0 });',
    '        io.observe(sentinel);',
    '      } else {',
    '        var ticking = false;',
    '        var handler = function() {',
    '          if (ticking || fired) return;',
    '          ticking = true;',
    '          setTimeout(function() { ticking = false; check(); if (fired) window.removeEventListener("scroll", handler); }, 100);',
    '        };',
    '        window.addEventListener("scroll", handler, { passive: true });',
    '        check();',
    '      }',
    '    };',
    '    _BGT.registerTrigger = function(options, callback) {',
    '      var eventKey = options.eventKey;',
    '      var mode = options.mode;',
    '      var capHours = typeof options.capHours === "number" ? options.capHours : 24;',
    '      var self = _BGT;',
    '      function gate() {',
    '        if (!self.shouldShowEvent(eventKey, capHours)) return;',
    '        self.markEventSeen(eventKey, capHours);',
    '        try { callback(); } catch (e) {}',
    '      }',
    '      if (mode === "exit-intent") {',
    '        var isMobile = (function() { try { if (window.matchMedia && window.matchMedia("(hover: none) and (pointer: coarse)").matches) return true; return window.innerWidth <= 768; } catch(e) { return window.innerWidth <= 768; } })();',
    '        if (!isMobile) {',
    '          document.addEventListener("mouseout", function(e) { if (e.clientY < 0) gate(); });',
    '        } else {',
    '          var lastY = window.scrollY; var upCnt = 0;',
    '          window.addEventListener("scroll", function() {',
    '            var cur = window.scrollY;',
    '            if (cur < lastY && lastY - cur > 40) { upCnt++; if (upCnt >= 3) gate(); } else { upCnt = 0; }',
    '            lastY = cur;',
    '          }, { passive: true });',
    '        }',
    '      } else if (mode === "scroll-depth") {',
    '        var thr = typeof options.threshold === "number" ? options.threshold : 60;',
    '        self.onScrollDepth(thr, gate);',
    '      }',
    '    };',
    '    window.__BG_TRIGGERS__ = _BGT;',
    '  }',
  ].join('\n');
}
