/**
 * build-meta.mjs
 *
 * workers/api/package.json의 version, git short hash, 빌드 시각을 읽어
 * workers/api/src/data/build-info.ts 를 자동 생성한다.
 *
 * 실행 방법 (workers/api 폴더 기준):
 *   node ../../scripts/build-meta.mjs
 *
 * 생성된 build-info.ts 는 .gitignore 에 등록되어 git 추적 대상이 아님.
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── 경로 계산 ──────────────────────────────────────────────────
// 이 스크립트는 supasignup/scripts/ 에 위치.
// workers/api/package.json, workers/api/src/data/ 를 참조.
const repoRoot = resolve(__dirname, '..');
const pkgPath = resolve(repoRoot, 'workers/api/package.json');
const outDir = resolve(repoRoot, 'workers/api/src/data');
const outPath = resolve(outDir, 'build-info.ts');

// ── version ────────────────────────────────────────────────────
let version = 'unknown';
try {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  version = pkg.version ?? 'unknown';
} catch {
  console.warn('[build-meta] package.json 읽기 실패 — version = unknown');
}

// ── commit hash + dirty check ──────────────────────────────────
let commitSha = 'unknown';
try {
  const sha = execSync('git rev-parse --short HEAD', { cwd: repoRoot, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim();
  const dirty = execSync('git status --porcelain', { cwd: repoRoot, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim();
  commitSha = dirty.length > 0 ? `${sha}-dirty` : sha;
} catch {
  console.warn('[build-meta] git 명령 실패 — commit_sha = unknown');
}

// ── build time (ISO 8601 UTC) ──────────────────────────────────
const buildTime = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');

// ── 출력 ──────────────────────────────────────────────────────
mkdirSync(outDir, { recursive: true });

const content = `// AUTO-GENERATED by scripts/build-meta.mjs — DO NOT EDIT
export const BUILD_VERSION = '${version}';
export const BUILD_COMMIT_SHA = '${commitSha}';
export const BUILD_TIME = '${buildTime}';
`;

writeFileSync(outPath, content, 'utf8');
console.log(`[build-meta] 생성 완료: ${outPath}`);
console.log(`  version:    ${version}`);
console.log(`  commit_sha: ${commitSha}`);
console.log(`  build_time: ${buildTime}`);
